config/routes.rb
ProgrammersNotebook::Application.routes.draw do

  root :to => 'notes#index'
  match 'notes/create' => 'notes#create'
  match 'notes/search/:title' => 'notes#search'
  match 'notes/all' => 'notes#all'
  match 'admin' => 'notes#new'
  match 'login' => 'notes#login', :as => :login
  resources :notes

end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::FullTextSearch
  field :title, type: String
  field :content, type: String
  fulltext_search_in :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notes_controller.rb
 class NotesController < ApplicationController
  require 'coderay'
  respond_to :json
  before_filter :is_logged_in?, :only => [:new, :create, :all, :edit, :update]

  def is_logged_in?
    if session[:user]
      return true
    else
      redirect_to :login
    end
  end

  def login
    if request.post?
      if params[:password] == SECRET
        session[:user] = true
        redirect_to :action => :new
      else
        redirect_to :login
      end
    end
  end

  def index
    @note = Note.new
  end

  def new
    @note = Note.new
  end

  def search
    @notes = Note.fulltext_search(params[:title])
    @notes.each do |n|
      n.content = CodeRay.scan(n.content, :ruby).div(:css => :class)
    end
    respond_with @notes
  end

  def create
    @note = Note.new(title: params[:title], content: params[:content])
    if @note.save
      render :text => true
    else
      render :text => false
    end
  end

  # Returns all code snippets for view and editing
  def all
    @notes = Note.order_by([:title, :desc])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update_attributes!(params[:note])
      flash[:notice] = "Updated Successfully"
      redirect_to :action => :all
    else
      logger.debug "Updating #{@note.id} failed."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All the Codez</title>
  <%= stylesheet_link_tag "application" %>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class='header_content'>
      <%= link_to "All the Codez", :root %>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/notes/all.html.erb
<% @notes.each do |n| %>  
  <h1><%= link_to(n.title, edit_note_path(n)) %></h1>
  <%= CodeRay.scan(n.content, :ruby).div(:css => :class).html_safe %>
<% end -%>

app/views/notes/edit.html.erb
<%= form_for @note do |f| -%>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <%= f.submit "Update", :disable_with => 'Updating...' %>
<% end -%>

app/views/notes/index.html.erb
<%= form_for @note do |f| -%>
  <%= label_tag :note_search, "Whatcha Want?", :id => 'search_label' %>
  <%= f.text_field :title, :id => "note_search", :autocomplete => "off" %>
<% end -%>

<% if session[:user] %>
  <button class="btn success" id="new_code_button"><%= link_to "Looking to add some code?", new_note_path %></button>
<% end -%>

<div id="result"></div>

app/views/notes/login.html.erb
  <div class="span8" id="login">
    <h1>Open Says Me!</h1>
    <%= form_tag "/login" %>
      <%= text_field_tag :password %>
      <%= submit_tag "Login" %>
    </div>

app/views/notes/new.html.erb
<h1>Task</h1>
<%= text_field_tag :task %>

<textarea id="note_content">

</textarea>
<br>

<button class="btn primary" id="note_submit"><a href="#" id="note_form_submit">Add Code</a></button>